version: "2"
services:
  api:
    build: .
    command: "pm2-docker process.json --web"
    ports:
      - "3051:3000"
      - "9551:9615"
    depends_on:
       - mongodb
    environment:
      NODE_ENV: development
      MONGODB_HOST: mongodb
      MONGODB_PORT: mongodb
      MONGODB_DATABASE: "docker_aws_example"
    volumes:
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    volumes:
      - "mongodb:/data/db"
    command: --smallfiles --rest

volumes:
  mongodb:
    external:
      name: mongodb

networks:
  default:
    driver: bridge